In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split

## Data Overview for Classification Problem

In [4]:
#brand csv
behold_brands = pd.read_csv('behold_brands.csv')
behold_brands.shape

(162, 10)

In [5]:
behold_brands.iloc[5,:]

brand_id                                  01EFJFYPRSP57FG4WC6NN3W4AX
brand                                          Ancient Greek Sandals
brand_value                               Handmade / Artisan Crafted
bio                Ancient Greek Sandals are handmade locally by ...
quote              A luxury, keep-forever version of the roadside...
quote_attribute                                             Vogue UK
intro              According to an Ancient Greek myth, the gods a...
lifestyle_copy     Our Thais in Natural under the sun, Get ready ...
short_bio          Handmade leather sandals with traditional tech...
listing_bio        Behold Ancient Greek Sandals! For when you don...
Name: 5, dtype: object

In [7]:
#Behold Products
behold_products = pd.read_excel('Behold+product+data+04262021.xlsx',header = 0)
behold_products.shape

(61355, 11)

In [250]:
behold_products.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61355 entries, 0 to 61354
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           61355 non-null  object
 1   brand                61355 non-null  object
 2   brand_category       60896 non-null  object
 3   name                 61354 non-null  object
 4   details              9200 non-null   object
 5   created_at           61355 non-null  object
 6   brand_canonical_url  61355 non-null  object
 7   description          51238 non-null  object
 8   brand_description    51234 non-null  object
 9   brand_name           61354 non-null  object
 10  product_active       61355 non-null  bool
dtypes: bool(1), object(10)
memory usage: 4.7+ MB

In [41]:
behold_products

,product_id,brand,brand_category,name,details,created_at,brand_canonical_url,description,brand_description,brand_name,product_active
0,01EX0PN4J9WRNZH5F93YEX6QAF,Two,Unknown,Khadi Stripe Shirt-our signature shirt,NaN,2021-01-27 01:17:19.305 UTC,https://two-nyc.myshopify.com/products/white-k...,Our signature khadi shirt\navailable in black ...,Our signature khadiÂ shirt\n\navailable in blac...,Khadi Stripe Shirt-our signature shirt,True
1,01F0C4SKZV6YXS3265JMC39NXW,Collina Strada,Unknown,RUFFLE MARKET DRESS LOOPY PINK SISTINE TOMATO,NaN,2021-03-09 18:43:10.457 UTC,https://collina-strada-2.myshopify.com/product...,Mid-length dress with ruffles and adjustable s...,Mid-length dress with ruffles and adjustable s...,RUFFLE MARKET DRESS LOOPY PINK SISTINE TOMATO,True
2,01EY4Y1BW8VZW51BWG5VZY82XW,Cariuma,Unknown,IBI Slip On Raw Red Knit Sneaker Women,NaN,2021-02-10 02:58:59.591 UTC,https://cariuma.myshopify.com/products/ibi-sli...,IBI Slip On Raw Red Knit Sneaker Women,IBI Slip On Raw Red Knit Sneaker Women,IBI Slip On Raw Red Knit Sneaker Women,False
3,01EY50E27A0P5V6KCW01XPDB43,Cariuma,Unknown,IBI Slip On Black Knit Sneaker Women,NaN,2021-02-10 03:40:52.842 UTC,https://cariuma.myshopify.com/products/ibi-sli...,IBI Slip On Black Knit Sneaker Women,IBI Slip On Black Knit Sneaker Women,IBI Slip On Black Knit Sneaker Women,False
4,01EY6DWHC2W5HPNEGXKEJ4A1CX,Cariuma,Unknown,CATIBA PRO Skate Black Suede and Canvas Contra...,NaN,2021-02-10 16:55:13.024 UTC,https://cariuma.myshopify.com/products/catiba-...,NaN,NaN,CATIBA PRO Skate Black Suede and Canvas Contra...,False
...,...,...,...,...,...,...,...,...,...,...,...
61350,01EYB5ERGYPFNGM6C9QK7Q9EV0,Nomasei,SandalsSales,BowVida Mule in Black Suede Kidskin,"Feminine flat mules.\nSquare shape, V line on ...",2021-02-12 13:04:05.149 UTC,https://www.nomasei.com/en/produit/bowvida-mul...,The flat BowVida mule in black suede is the id...,The flat BowVida mule in black suede is the id...,BowVida Mule in Black Suede Kidskin,False
61351,01EHWTBFP368Q035FW95TRJDAY,Nomasei,Flat sandalsArchives,Sandale Vida Mule In Tangerine Suede Kidskin,"Feminine flat mules.\nSquare shape, V line on ...",2020-09-10 20:12:19.514 UTC,https://www.nomasei.com/en/produit/vida-mule-i...,The flat Vida mule in tangerine suede is the c...,The flat Vida mule in tangerine suede is the c...,Sandale Vida Mule In Tangerine Suede Kidskin,False
61352,01EHWTCFTPPSCW10D4XBQZF28H,Nomasei,Flat sandalsArchives,BowVida Mule in Fuschia Suede Kidskin,"Feminine flat mules.\nSquare shape, V line on ...",2020-09-10 20:12:52.43 UTC,https://www.nomasei.com/en/produit/mule-bowvid...,The flat BowVida mule in fuschia suede is the ...,The flat BowVida mule in fuschia suede is the ...,BowVida Mule in Fuschia Suede Kidskin,False
61353,01EYB5B5FH7JESXF82ZEMVXZMS,Nomasei,SandalsSales,Vida Mule in Silver Metalized Leather,"Feminine flat mules.\nSquare shape, V line on ...",2021-02-12 13:02:07.344 UTC,https://www.nomasei.com/en/produit/vida-mule-i...,The flat Vida mule in silver metalized leather...,The flat Vida mule in silver metalized leather...,Vida Mule in Silver Metalized Leather,False
61354,01EHWTF4VNZ6FPF2836A0CFEEG,Nomasei,Flat sandalsArchives,BowVida Mule in Bronze Metalized Leather,"Feminine flat mules.\nSquare shape, V line on ...",2020-09-10 20:14:19.502 UTC,https://www.nomasei.com/en/produit/bowvida-mul...,The flat BowVida mule in bronze leather is the...,The flat BowVida mule in bronze leather is the...,BowVida Mule in Bronze Metalized Leather,False

In [1]:
behold_products.iloc[0,10]

NameError: name 'behold_products' is not defined

**notes**

 - use `description` vs `brand_description`
 - can't join brand dataset to product dataset
 - would involve using outcome to feature engineer
 - `created_at` does not seem meaningful
 - unsure of `product_active` meaning
 - `brand_name` & `name` not identical across entire dataset
 - weather/climate feature would be useful

In [43]:
#attribute tags
attr_tags = pd.read_csv('usc_additional_tags.csv')
attr_tags.shape

(97420, 4)

In [44]:
attr_tags.head(5)

,product_id,product_color_id,attribute_name,attribute_value
0,01E5ZXP5H0BTEZT9QD2HRZJ47A,01E5ZXP5JCREDC7WJVMWHK5Q40,materialclothing,linenblend
1,01E5ZXP5H0BTEZT9QD2HRZJ47A,01E5ZXP5JCREDC7WJVMWHK5Q40,materialclothing,cottonblend
2,01E5ZXP5H0BTEZT9QD2HRZJ47A,01E5ZXP5JCREDC7WJVMWHK5Q40,style,modern
3,01E5ZXP5H0BTEZT9QD2HRZJ47A,01E5ZXP5JCREDC7WJVMWHK5Q40,style,businesscasual
4,01E5ZXP5H0BTEZT9QD2HRZJ47A,01E5ZXP5JCREDC7WJVMWHK5Q40,style,classic

**notes**
- can join products on product_id *left join to since dimensions do not match*
    - will require some preprocessing(multiple attr_names/values for one product)
    - combine into list for each unique id then join to main dataset

In [45]:
#pivot df
grouped_tags = pd.DataFrame(attr_tags.groupby(['product_id','attribute_name'])
                            .attribute_value.apply(lambda x:" ".join(set(x)))).reset_index()

pivoted_tags = grouped_tags.pivot(index='product_id',columns=['attribute_name'],values='attribute_value').reset_index()

color_id_df =attr_tags[['product_id','product_color_id']].drop_duplicates() #multiple colors for many product ids; join to main df seperately

In [46]:
pivoted_tags[pivoted_tags.product_id =='01E6078G3GRATF2C96VKYYWSGD']

attribute_name,product_id,additionalcolor,beltbucklematerial,beltbuckleshape,beltclosure,beltmaterial,beltwidth,calfwidth,category,classbelts,...,subcategorysweater,subcategorysweatshirtandhoodie,subcategorytop,sunglassframematerial,sweatshirtandhoodieclosure,toeexposure,toestyle,trend,uppermaterial,wash
3966,01E6078G3GRATF2C96VKYYWSGD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bottom,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
#gotta figure out what to do about the colors
pivoted_tags.head(15)

attribute_name,product_id,additionalcolor,beltbucklematerial,beltbuckleshape,beltclosure,beltmaterial,beltwidth,calfwidth,category,classbelts,...,subcategorysweater,subcategorysweatshirtandhoodie,subcategorytop,sunglassframematerial,sweatshirtandhoodieclosure,toeexposure,toestyle,trend,uppermaterial,wash
0,01DMBRYVA2P5H24WK0HTK4R0A1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bottom,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01DMBRYVA2PEPWFTT7RMP5AA1T,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blazerscoatsjackets,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01DMBRYVA2Q2ST7MNYR6EEY4TK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,onepiece,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01DMBRYVA2S5T9W793F4CY41HE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,accessory,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01DMBRYVA2ZFDYRYY5TRQZJTBD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,shoe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,01DMHCNT41E14QWP503V7CT9G6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,accessory,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,01DPC6Z5K3ZB8KZ0M6YW7Z4JX8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sweater,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,01DPC8AMPE4CZHMJETF1Q8VEN0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,blazerscoatsjackets,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,01DPC9GSTT72KHNN0MNDNKH7RD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,accessory,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,01DPC9XNR3XBH3HAAQYGYKRJ5H,NaN,NaN,NaN,NaN,NaN,NaN,NaN,onepiece,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,01DPCB2KEAVXXKFVM7FXBNE4VY,NaN,NaN,NaN,NaN,NaN,NaN,medium,shoe,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,pointedtoe,NaN,suede,NaN
11,01DPCDEF6SYX2E1NT5X7HJBFGY,pinks,NaN,NaN,NaN,NaN,NaN,NaN,accessory,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,01DPCG1C1P0MQAV9NMS3N1TDAA,greens pinks blacks,NaN,NaN,NaN,NaN,NaN,NaN,onepiece,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,01DPCHNEW5F2RHJQ3NJMVPK6SE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,sweater,NaN,...,pullover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,01DPCHNQM0PA0SXZZZX85PF2ZJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bottom,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,rawhem,NaN,lightblue

In [48]:
#added colors for all products;since multiple colors for each product, product_id is not unique
pivoted_tags=pivoted_tags.merge(color_id_df,how='left',on='product_id').sort_values('product_id')
pivoted_tags[pivoted_tags.product_id =='01E6078G3GRATF2C96VKYYWSGD']

,product_id,additionalcolor,beltbucklematerial,beltbuckleshape,beltclosure,beltmaterial,beltwidth,calfwidth,category,classbelts,...,subcategorysweatshirtandhoodie,subcategorytop,sunglassframematerial,sweatshirtandhoodieclosure,toeexposure,toestyle,trend,uppermaterial,wash,product_color_id
5513,01E6078G3GRATF2C96VKYYWSGD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bottom,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01E6078M3MMSAETKP9PD5DPRR2
5512,01E6078G3GRATF2C96VKYYWSGD,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bottom,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01E6078G42KZPG57NCP4YG1TBB

In [237]:
#number of products with additional features from the attribute set
len(list(set(behold_products.product_id) & set(pivoted_tags.product_id)))

3780

**note**
 - alot fewer products than hoped for 
 - instead of joining to create new features may can add to current features (details,etc)
 - can extract similar data from products df and add to these new features
 - definitely going to be problematic with so many missing features
 - nonunique product_id due to multiple colors may cause issues when trying to merge with main product dataset

In [21]:
#truncated catalogue
catalogue = pd.read_csv('truncated_catalog.csv')
catalogue.shape

(42373, 7)

**notes**
 - no product id; doesn't seem useful for prediction